### ISSUE TITLE
Does the "--nohp" option return siRNAs only?

### ISSUE THREAD

**Issue by uceleste** [MikeAxtell/ShortStack#101]
Dear developers,

I have installed and tested ShortStack using your test data. Everything worked perfectly. I just need a little confirmation.
For my analysis I will only need siRNAs. For this reason I have not installed RNAfold and I have run the program with the "--nohp" option. So, can you confirm me that all the sequences reported in the gffs refer exclusively to siRNAs?

Thanks

**Comment by MikeAxtell** [comment]
Glad to hear it is working for you.
If you run with --nohp the script will not be able to analyze whether or not any of the discovered clusters are MIRNAs or not. However you cannot thus conclude everything is siRNA. ShortStack only finds clusters of aligned sRNA reads. These could be microRNAs, siRNAs, degraded bits of longer RNAs, or any combination thereof. Caveat emptor.


--
Michael J. Axtell, Ph.D.
Professor of Biology
Pennsylvania State University
https://sites.psu.edu/axtell
https://plantsmallrnagenes.science.psu.edu
