### ISSUE TITLE
Annotation of sRNA loci

### ISSUE THREAD

**Issue by midhatubaid** [MikeAxtell/ShortStack#104]
Dear Dr. Axtell, 
I have just finished sRNA analysis for Arabidopsis using ShortStack 3.3 (on cyverse.org). In order to identify different sRNA subclasses, I used the Arabidopsis sRNA loci file (https://plantsmallrnagenes.science.psu.edu/genomes.php?id=50). Since this reference loci file has genomic coordinates but does not have the corresponding genomic features (e.g. gene, promoter, UTR, intergenic region, etc.), I want to annotate the resulting count files also with genomic features corresponding to genomic coordinates from the ath-b10 genome build. Could you please let me know what program you use to annotate these genomic intervals?

**Comment by MikeAxtell** [comment]
This is not a ShortStack question. NCBI datasets, phytozome, and Arabidopsis.org are 3 examples of locations where genomic datasets can be acquired for *Arabidopsis thaliana*.
