### ISSUE TITLE
csfasta support

### ISSUE THREAD

**Issue by vojtace** [MikeAxtell/ShortStack#106]
Hi,
I would like to point out that since version 1.3.0 bowtie does not support colorspace data. I think that this information should be updated in the manual, which says that ShortStack can process .csfasta, but this is true only if you downgrade bowtie.
Thanks!

**Comment by MikeAxtell** [comment]
Thank you. In the newest version of ShortStack, 4.0, all support for colorspace data is dropped. New version is currently in alpha testing and can be accessed by interested users on the ShortStack4 branch of the GitHub repo. Once we complete testing I will merge to master and make a release.
