### ISSUE TITLE
QIAseq® miRNA Library paired-end reads for sRNA-seq experiment

### ISSUE THREAD

**Issue by DiegoZavallo** [MikeAxtell/ShortStack#120]
Hi Mike, 
I have a colaborator that ask me to analyze some sRNA data for her experiment.
She gave me the raw data and some information about how they done it in the sequencing service.
The first thing that strike me is the fact that the library preparation was made with this kit [QiagensmRNAmiRNAProtocol.pdf](https://github.com/MikeAxtell/ShortStack/files/11054615/QiagensmRNAmiRNAProtocol.pdf) which specifically said that is for miRNAs and I quote :"Unlike most cellular RNAs, mature miRNAs possess both a 3’ hydroxyl group and a 5’ phosphate group. This allows adapters to be specifically ligated to both the 3’ end and 5’ end of miRNAs enabling universal reverse transcription and library preparation of mature miRNAs, while minimizing the background from other RNA species"
Do you think that it also will sequence siRNAs in their many forms (21-22 and 24nt?)

The protocol also said that the library should be single end for obvious reasons, but the seq service did a pair end libraries! Moreover, R1 have 75bp and R2 have 50bp and of course they overlap almost entirely (reverse complement)

I read in some thread that someone have a similar situation and you recommend him to try ShortStack, but if I´m not mistaken it does not suport pair end reads, right?
Others recommend him to reverse complement the R2 reads (after removing adaptors) and simply paste them into the R1 files.
Any thoughts on that?
Honestly, I dont know why they did the libraries pair end (or only for miRNAs in that matter) 

Do you have any recommendation on how to proceed?

Thanks a lot!

Best

Diego

**Comment by MikeAxtell** [comment]
All the Dicer-produced small RNAs have a 5'-monophosphate and 3' hydroxyl, and RNA ligation has been the standard in sRNA-seq library construction for a long time. Nothing different there.

Just throw out the R2 reads. Use only the R1 reads for ShortStack (and any other analysis).

**Comment by DiegoZavallo** [comment]
Hi Mike, thanks for your answer.
I thought that might be the case, but the enphasis wiht miRNAs on the protocol make my doubt.

Great!, I will use only R1 for the analysis

Best

Diego
