### ISSUE TITLE
Trying to run ShortStack with the --knownRNAs argument, it does not work

### ISSUE THREAD

**Issue by ozambadam** [MikeAxtell/ShortStack#123]
Hi, I am trying to run this package using the --knownRNAs function and It is not recognized:

`Unknown option: knownrnas

Unknown arguments: 6 ../sly_miRBase.fa`

**Comment by MikeAxtell** [comment]
The option is `--knownRNAs` with capital letters for RNA.

**Comment by ozambadam** [comment]
I am using capital letters.

My command is: 

`ShortStack --genomefile ../TPMVd_genome.fa --readfile *.fq --threads 6 --outdir with_DB --knownRNAs ../sly_miRBase.fa`

Still doesn´t work

![image](https://user-images.githubusercontent.com/94479457/228353694-995eaf5a-757a-4bc2-8299-9eb75e5552ea.png)

**Comment by MikeAxtell** [comment]
This is likely part of an ongoing issue / defect in conda (not ShortStack) ... there are cases where just calling `conda install [tool]` does not give the latest version of the tool. There are lots of discussions about this conda issue. For instance:

https://github.com/bioconda/bioconda-recipes/issues/24199

https://github.com/conda/conda/issues/9905

You can also try two steps, and specifying the release you wish to obtain:

`conda create --name ShortStack4`
`conda install shortstack=4.0.0`

**Comment by ozambadam** [comment]
Thanks a lot, it is working now
