### ISSUE TITLE
complexity measurement

### ISSUE THREAD

**Issue by thalescherubino** [MikeAxtell/ShortStack#139]
Hi Mike.

A feature that I found useful in ShortStack 3 is gone. The reported "complexity" values did help curating bona fide miRNAs and identifying false positives. Could you re implement that?

Best,

**Comment by MikeAxtell** [comment]
Sorry for the slow response on this. This can be easily computed using columns 7 and 8 in the Results.txt file. Column 7 ('Reads') gives the total number of reads aligned at the locus. Column 8 ('DistinctSequences') gives the the total of distinct sRNA sequences aligned at the locus. A given Distinct Sequence can have one or more associated reads. These are the two numbers that in the past were used to compute "complexity".

Column 8 in Results.txt had been previously mis-named as "UniqueReads" and the description in the README was incorrect. As of release 4.0.3 the description in the README has been fixed, and the name changed to "DistinctSequences".
