### ISSUE TITLE
Results 

### ISSUE THREAD

**Issue by aayoungfish** [MikeAxtell/ShortStack#145]
Hello, Dr Axtell. 

I have two batches of data, both of which are of the same species, and I ran two separate analyses to get two results files. But I found that their clusters are actually completely different, and only the miRNAs have their own unique geneids that I can discern. Is there any way to match the cluster in result 1 to the cluster in result 2?   
Because my batch 1 processing is completely different from the processing of batch 2, if I merge all the bam files in one command line operation, will it have a big impact on my results? 

I'm looking forward to hearing from you! 
Thanks！
Emily

**Comment by MikeAxtell** [comment]
ShortStack's naming of de novo clusters is simply sequential for each run. There is no inherent correspondence of names to specific chromosomal addresses between runs. You can always use bedtools intersect (or similar approaches) to find overlaps of clusters called in different runs.

As for merging your BAM files before running ShortStack, that is fine in a technical sense. You mentioned that you used methods that are "completely different" for the different data sets, so only you can answer how appropriate the merge would be.
