### ISSUE TITLE
Inconsistencies Between Default Settings in Documentation and Code

### ISSUE THREAD

**Issue by spriego** [MikeAxtell/ShortStack#148]
Dear Mike,

I've noticed some discrepancies between the default settings outlined in ShortStack's documentation and the actual code:

1. In the documentation, `--mmap` is listed as defaulting to `f`, but in the code (line 535), it's actually set to `u`.
2. Regarding `--mincov`, the documentation indicates a default value of `2`, yet in the code (line 601), it's set to `1`.

**Comment by MikeAxtell** [comment]
Thanks for pointing these errors out. I've updated the README to correct them.

The `--mmap` setting of `u` is the true default, and it is the superior setting according to our previous work <https://doi.org/10.1534/g3.116.030452>  ... so it was just the README that was wrong, not the software.
