### ISSUE TITLE
Alert of syntax warning 

### ISSUE THREAD

**Issue by nponts** [MikeAxtell/ShortStack#157]
Hi,
Not really a blocking issue yet, just a warning on a bad syntax: SyntaxWarning: invalid escape sequence '\s'
It occurs on 12 lines, running under python 3.12.3 (ShortStack was installed with conda).
I'm just letting you know :)
Thank you for the tool!
Cheers,
NP

**Comment by MikeAxtell** [comment]
Thanks NP, sorry for the slow response (vacation). Not seeing this on my end, my dev environment has been python 3.10.14. I'm working on a major update to ShortStack and I'll check to remove the deprecated escape symbols like this in the release.

Mike


From: nponts ***@***.***>
Date: Wednesday, July 31, 2024 at 3:33 AM
To: MikeAxtell/ShortStack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MikeAxtell/ShortStack] Alert of syntax warning (Issue #157)

Hi,
Not really a blocking issue yet, just a warning on a bad syntax: SyntaxWarning: invalid escape sequence '\s'
It occurs on 12 lines, running under python 3.12.3 (ShortStack was installed with conda).
I'm just letting you know :)
Thank you for the tool!
Cheers,
NP

**Comment by MikeAxtell** [comment]
Thanks again for this. Upgrading my python from 3.10.14 to 3.12.3 revealed these syntax warnings to me too. I've made the fixes in my uncommitted development code. The fixes will be included in the next release, which should be forthcoming soon. Until then I will leave this thread open.

**Comment by nponts** [comment]
Dear Mike,
Was me who was on vacation this time :)
I'm looking forward to the next release, thank you for the work!
Cheers!

**Comment by MikeAxtell** [comment]
Fixed as of release 4.1.0
