### ISSUE TITLE
warning in STDERR about non-numeric argument in de-novo cluster identification/analysis phase

### ISSUE THREAD

**Issue by shahsam** [MikeAxtell/ShortStack#22]
Occasional warning about non-numeric arguments comes up in STDERR while running ShortStack v 3.0:
"Argument "19C1" isn't numeric in addition (+) at ./ShortStack line 3982"
The characters (19C1) following "Argument" in above warning varies from file to file.

**Comment by MikeAxtell** [comment]
This occurs when a potential mature miRNA alignment has one or more mismatches to the reference genome. This is rare in our testing so far but will probably occur in experimental settings with a polymorphic or poor-quality reference assembly. Should be a quick fix...

**Comment by MikeAxtell** [comment]
I should add that the bug is potentially serious in those cases since such miRNAs can't be discovered.

**Comment by MikeAxtell** [comment]
Actually probably wasn't that serious. It looks like it would only be affecting the text-based display of discovered MIRNA loci.

Anyway, try commit eb3e3eb... in which I think the bug is fixed. Please let me know if that fixed it.

**Comment by shahsam** [comment]
thanks, I am checking now.

**Comment by shahsam** [comment]
I finished the run with the new commit for the same file, no warnings anymore. Thanks!

**Comment by MikeAxtell** [comment]
OK, this bugfix will make it into the next release, which will be 3.1
