### ISSUE TITLE
Too many MIRNA duplex

### ISSUE THREAD

**Issue by xingwu2** [MikeAxtell/ShortStack#28]
Hi Mike:

I used the Shortstack Version 2.1.0 on my small RNA seq data, and it generated ~55000 MIRNA clusters. Almost each MIRNA cluster has multiple miRNA duplexes. Now I don't know which duplex to choose for the downstream analyses. Should I select the duplex based on score of the duplex of the number of alignments, the more alignments the more confident you are? 

Here is a screenshort of one of my MIRNA clusters, I hope it can make my question more clear.

Alignment summary by RNA size:
RNA_SIZE	ALIGNMENTS
<20	2991
20	6828
21	14646
22	100895
23	16957
24	493
>24	251

Duplex: seq57 / seq251
Sequences: AAGAGCUUGAGGAAGUGAUG / UGAUUUCCUUCGGUUCCUCU
Score: 0.986
Verdict: PASS
RNA Lengths: 20 / 20
Alignments: 19 / 2785
Median mapping positions (XX): 2 / 1
Median placement probabilities (XZ): 0.670 / 1.000

Duplex: seq127 / seq211
Sequences: GAGAUGGGAGGGUCGGUAAAG / UUGCCGAUUCCACCCAUUCCU
Score: 0.936
Verdict: PASS
RNA Lengths: 21 / 21
Alignments: 489 / 507
Median mapping positions (XX): 2 / 2
Median placement probabilities (XZ): 0.670 / 0.670

Duplex: seq112 / seq205
Sequences: GGAGAUGGGAGGGUCGGUAAAG / UUGCCGAUUCCACCCAUUCCUA
Score: 0.936
Verdict: PASS
RNA Lengths: 22 / 22
Alignments: 70888 / 28360
Median mapping positions (XX): 2 / 2
Median placement probabilities (XZ): 0.670 / 0.670

Duplex: seq19 / seq268
Sequences: GGAGAAGAGCUUGAGGAAGUGA / AUUUCCUUCGGUUCCUCUCU
Score: 0.936
Verdict: PASS
RNA Lengths: 22 / 20
Alignments: 134 / 17
Median mapping positions (XX): 1 / 1
Median placement probabilities (XZ): 1.000 / 1.000

Thank you so much

Xing Wu

University of Illinois

**Comment by MikeAxtell** [comment]
Hi Xing, thanks for your message.
I suggest upgrading to the latest ShortStack version, 3.3. The 'multiple'
miRNA duplexes that I was using in versions 2.x has been scrapped -- too
confusing.

Or, just take the highest scoring duplex from each miRNA found.

- Mike


On Tue, Sep 29, 2015 at 12:02 AM, xingwu2 <notifications@github.com> wrote:

> Hi Mike:
>
> I used the Shortstack Version 2.1.0 on my small RNA seq data, and it
> generated ~55000 MIRNA clusters. Almost each MIRNA cluster has multiple
> miRNA duplexes. Now I don't know which duplex to choose for the downstream
> analyses. Should I select the duplex based on score of the duplex of the
> number of alignments, the more alignments the more confident you are?
>
> Here is a screenshort of one of my MIRNA clusters, I hope it can make my
> question more clear.
>
> Alignment summary by RNA size:
> RNA_SIZE ALIGNMENTS
> <20 2991
> 20 6828
> 21 14646
> 22 100895
> 23 16957
> 24 493
>
> 24 251
>
> Duplex: seq57 / seq251
> Sequences: AAGAGCUUGAGGAAGUGAUG / UGAUUUCCUUCGGUUCCUCU
> Score: 0.986
> Verdict: PASS
> RNA Lengths: 20 / 20
> Alignments: 19 / 2785
> Median mapping positions (XX): 2 / 1
> Median placement probabilities (XZ): 0.670 / 1.000
>
> Duplex: seq127 / seq211
> Sequences: GAGAUGGGAGGGUCGGUAAAG / UUGCCGAUUCCACCCAUUCCU
> Score: 0.936
> Verdict: PASS
> RNA Lengths: 21 / 21
> Alignments: 489 / 507
> Median mapping positions (XX): 2 / 2
> Median placement probabilities (XZ): 0.670 / 0.670
>
> Duplex: seq112 / seq205
> Sequences: GGAGAUGGGAGGGUCGGUAAAG / UUGCCGAUUCCACCCAUUCCUA
> Score: 0.936
> Verdict: PASS
> RNA Lengths: 22 / 22
> Alignments: 70888 / 28360
> Median mapping positions (XX): 2 / 2
> Median placement probabilities (XZ): 0.670 / 0.670
>
> Duplex: seq19 / seq268
> Sequences: GGAGAAGAGCUUGAGGAAGUGA / AUUUCCUUCGGUUCCUCUCU
> Score: 0.936
> Verdict: PASS
> RNA Lengths: 22 / 20
> Alignments: 134 / 17
> Median mapping positions (XX): 1 / 1
> Median placement probabilities (XZ): 1.000 / 1.000
>
> Thank you so much
>
> Xing Wu
>
> University of Illinois
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MikeAxtell/ShortStack/issues/28>.
>



-- 
Michael J. Axtell, Ph.D.
Associate Professor
Dept. of Biology
Penn State University
http://sites.psu.edu/axtell
Twitter: @MikeAxtell

**Comment by xingwu2** [comment]
Thank you so much for the reply. Also, can I just simply think the clusters that have a DicerCall of 20 -24nt but not annotated as MIRNA are the precursors of siRNA?  If so, how should I find the targets of the siRNAs? Can I blast the precursors against genome to find the targets? 

Thank you again for your tremendous work. 

-Xing

**Comment by MikeAxtell** [comment]
We usually think of clusters with a DicerCall of 20-24, and a strand of .
(unstranded) as endogenous siRNAs.

There are numerous target prediction tools out there for miRNA and siRNAs.
Perhaps take a look at them. We like targetfinder from the Carrington Lab,
and we have our own, GSTAr.pl, available on github. These are mostly for
miRNAs. The rules for het-siRNAs are not really clear.

On Tue, Sep 29, 2015 at 12:50 PM, xingwu2 <notifications@github.com> wrote:

> Thank you so much for the reply. Also, can I just simply think the
> clusters that have a DicerCall of 20 -24nt but not annotated as MIRNA are
> the precursors of siRNA? If so, how should I find the targets of the
> siRNAs? Can I blast the precursors against genome to find the targets?
>
> Thank you again for your tremendous work.
>
> -Xing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MikeAxtell/ShortStack/issues/28#issuecomment-144118122>
> .
>



-- 
Michael J. Axtell, Ph.D.
Associate Professor
Dept. of Biology
Penn State University
http://sites.psu.edu/axtell
Twitter: @MikeAxtell

**Comment by MikeAxtell** [comment]
Xing, did upgrading to 3.3 solve your issue? If so I will close this issue on github.

Cheers,
Mike

**Comment by xingwu2** [comment]
HI Mike:

I didn’t upgrade to 3.3, and I just picked the miRNA duplexes with the highest scores. I should reply you, I am sorry. 

Best

Xing

**Comment by MikeAxtell** [comment]
No worries, and thanks for the feedback. I am closing this issue.
