### ISSUE TITLE
How to only count the alignments without any other analyses in the newest Shortstack

### ISSUE THREAD

**Issue by xingwu2** [MikeAxtell/ShortStack#30]
Hi Alex:

I am working on a small RNAseq data using ShortStack-3.3. I trimmed the raw reads into 21-24 nt, removed the miRNA, tRNA and rRNA from the library and assumed the rest are siRNAs. My plan is to align those siRNAs to my de novo transcriptome generated by Trinity from a independent RNAseq experiment and count how many siRNAs aligned to  each de novo contig. Then combine the gene expression data and siRNA alignments data together to try to explain something.

I really don't know about how to count the small RNA alignments, neither only count the unique mapping reads nor use EM to handle multiple mapping reads satisfies this case. I do agree with the method that ShortStack uses (--mmap u or -mmap f). Can I perform the alignment only using ShortStack and count how many siRNA alignments on each trinity contig? Rather than using the Genome, is it appropriate to use the transcriptome as input. Do you think my analysis scheme has some big drawbacks? Also I know Butter does similar thing, but how to convert the output bam file into "real" count numbers?

Even though I work on soybean, but the soybean I sequenced is quite different from the reference genome, and also I am targeting some "novel siRNA" that do not exist in the reference genome. That is why I do not follow the common ShotStack workflow. 

Here is the command line I used in ShortStack

ShortStack --readfile ../../real_siRNA_library/B24/B_24_siRNA.fa --bowtie_cores 12 --nostitch --mismatch 0 -mmap u --align_only --genomefile ../../database/trinity_assembly/merged_trinity_assembly.fa 

Best

Xing

**Comment by MikeAxtell** [comment]
I suggest some changes:

When adapter trimming, do NOT throw our reads just because they are <21 or
> 24. Keep all sizes. This allows you to later tell if a cluster is from
degraded RNA (in which case a broad set of sizes, many of which are <21 or
>24 will be found) or is really an siRNA cluster.

Yes, you can align directly to your transcriptome. ShortStack will provide
raw read counts for each cluster it finds.

On Wed, Oct 28, 2015 at 1:33 AM, xingwu2 <notifications@github.com> wrote:

> Hi Alex:
>
> I am working on a small RNAseq data using ShortStack-3.3. I trimmed the
> raw reads into 21-24 nt, removed the miRNA, tRNA and rRNA from the library
> and assumed the rest are siRNAs. My plan is to align those siRNAs to my de
> novo transcriptome generated by Trinity from a independent RNAseq
> experiment and count how many siRNAs aligned to each de novo contig. Then
> combine the gene expression data and siRNA alignments data together to try
> to explain something.
>
> I really don't know about how to count the small RNA alignments, neither
> only count the unique mapping reads nor use EM to handle multiple mapping
> reads satisfies this case. I do agree with the method that ShortStack uses
> (--mmap u or -mmap f). Can I perform the alignment only using ShortStack
> and count how many siRNA alignments on each trinity contig? Rather than
> using the Genome, is it appropriate to use the transcriptome as input. Do
> you think my analysis scheme has some big drawbacks? Also I know Butter
> does similar thing, but how to convert the output bam file into "real"
> count numbers?
>
> Even though I work on soybean, but the soybean I sequenced is quite
> different from the reference genome, and also I am targeting some "novel
> siRNA" that do not exist in the reference genome. That is why I do not
> follow the common ShotStack workflow.
>
> Here is the command line I used in ShortStack
>
> ShortStack --readfile ../../real_siRNA_library/B24/B_24_siRNA.fa
> --bowtie_cores 12 --mismatch 0 -mmap u --align_only --genomefile
> ../../database/trinity_assembly/merged_trinity_assembly.fa
>
> Best
>
> Xing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MikeAxtell/ShortStack/issues/30>.
>



-- 
Michael J. Axtell, Ph.D.
Associate Professor
Dept. of Biology
Penn State University
http://sites.psu.edu/axtell
Twitter: @MikeAxtell
