### ISSUE TITLE
NAs in Counts.txt

### ISSUE THREAD

**Issue by xingwu2** [MikeAxtell/ShortStack#31]
HI Alex:

I used the ShortStack-3.3 to work on my small RNAseq data. I aligned multiple libraries to my de novo transcriptome with --mismatches 0 --nostitch --nohp --dicermin 21 in my command line. When I look at the Counts.txt file, I notice some observe count values are NA, and some are 0. Is NA equal to 0? And some observe counts are integers, some are fractions. Is this normal? 

Best

XIng

**Comment by MikeAxtell** [comment]
Are you sure? Looking at the actual perl code, the _obs columns will
be zero when no reads at the locus were present in the specified
read-group. The adjacent _mean and _stdev columns will be NA in those
cases.

If this is not the case, please send an example Counts.txt file so I
can check it out.

On Mon, Nov 2, 2015 at 12:34 PM, xingwu2 <notifications@github.com> wrote:
> HI Alex:
>
> I used the ShortStack-3.3 to work on my small RNAseq data. I aligned
> multiple libraries to my de novo transcriptome with --mismatches 0
> --nostitch --nohp --dicermin 21 in my command line. When I look at the
> Counts.txt file, I notice some observe count values are NA, and some are 0.
> Is NA equal to 0?
>
> Best
>
> XIng
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Michael J. Axtell, Ph.D.
Associate Professor
Dept. of Biology
Penn State University
http://sites.psu.edu/axtell
Twitter: @MikeAxtell

**Comment by xingwu2** [comment]
I am sorry, I was wrong. The observe counts are all numbers. Thank you so much!
