### ISSUE TITLE
total counts vary between alignment and sum of observed counts

### ISSUE THREAD

**Issue by xingwu2** [MikeAxtell/ShortStack#32]
Hi Alex:

I am sorry to bother you AGAIN.  

I used ShortStack-3.3 to analyze my data with -mmap u in the command line. When I want to normalize the raw counts into RPK, I find the number of valid alignments and the sum of obs_count are different. 

Here is the Log:

Starting alignment of ../../real_siRNA_library_ShortStack/B_control/B_control_siRNA.fq with bowtie command:
	bowtie -q -v 0 -p 12 -S -a -m 50 --sam-RG ID:B_control_siRNA ../../database/trinity_assembly/merged_trinity_assembly - < ../../real_siRNA_library_ShortStack/B_control/B_control_siRNA.fq
	Completed. Results are in temporary file ShortStack_1446230180/B_control_siRNA_readsorted.sam.gz pending final processing
	Unique mappers: 325811 / 14616408 (2.2 %)
	Multi mappers: 10963924 / 14616408 (75.0 %)
	Multi mappers ignored and marked as unmapped: 91633 / 14616408 (0.6 %)
	Non mappers: 3235040 / 14616408 (22.1 %)

Based on the alignments, ShortStack should count 325811 + 10963924 = 11289735 reads for B_control library. But the total observed counts for B_control library is only 8460184. Why the two numbers are different? Similar situation happens in other libraries. Which number should I use for normalization? 

Thank you very much for you patience and great work! 

Best

Xing

**Comment by MikeAxtell** [comment]
No problem. By "total observed counts for B_control library is only
8460184", I think you are referring to the sum of the reads found in the
Results.txt file?

If so, here's the deal: ShortStack finds clusters in the genome of
significant small RNA accumulation. But, genomic loci that produce very low
amounts of small RNAs will not be part of clusters. So, the total number of
primary alignments in the bam file will be more than the total number of
reads found in all of the discovered clusters.

The sensitivity of cluster discovery is adjustable with the ShortStack 3
options --mincov and --pad



On Tue, Nov 3, 2015 at 10:57 PM, xingwu2 <notifications@github.com> wrote:

> Hi Alex:
>
> I am sorry to bother you AGAIN.
>
> I used ShortStack-3.3 to analyze my data with -mmap u in the command line.
> When I want to normalize the raw counts into RPK, I find the number of
> valid alignments and the sum of obs_count are different.
>
> Here is the Log:
>
> Starting alignment of
> ../../real_siRNA_library_ShortStack/B_control/B_control_siRNA.fq with
> bowtie command:
> bowtie -q -v 0 -p 12 -S -a -m 50 --sam-RG ID:B_control_siRNA
> ../../database/trinity_assembly/merged_trinity_assembly - <
> ../../real_siRNA_library_ShortStack/B_control/B_control_siRNA.fq
> Completed. Results are in temporary file
> ShortStack_1446230180/B_control_siRNA_readsorted.sam.gz pending final
> processing
> Unique mappers: 325811 / 14616408 (2.2 %)
> Multi mappers: 10963924 / 14616408 (75.0 %)
> Multi mappers ignored and marked as unmapped: 91633 / 14616408 (0.6 %)
> Non mappers: 3235040 / 14616408 (22.1 %)
>
> Based on the alignments, ShortStack should count 325811 + 10963924 =
> 11289735 reads for B_control library. But the total observed counts for
> B_control library is only 8460184. Why the two numbers are different?
> Similar situation happens in other libraries. Which number should I use for
> normalization?
>
> Thank you very much for you patience and great work!
>
> Best
>
> Xing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MikeAxtell/ShortStack/issues/32>.
>



-- 
Michael J. Axtell, Ph.D.
Associate Professor
Dept. of Biology
Penn State University
http://sites.psu.edu/axtell
Twitter: @MikeAxtell

**Comment by xingwu2** [comment]
Ok, this makes sense to me. Thank you so much! Have a great day.
