### ISSUE TITLE
cutoff for phasescore

### ISSUE THREAD

**Issue by xingwu2** [MikeAxtell/ShortStack#33]
Hi Alex:

I used the ShortStack-3.3 to analyze my soybean small RNAseq data. I found many phased siRNAs have dicercall not equal to 21nt, for example 24nt, is this normal? Also If I want to set a confidence cutoff on PhaseScore, what would be a reasonable value for it? How about 100?

Best

Xing

**Comment by MikeAxtell** [comment]
Who is Alex?

Check the literature. there are examples of 24nt phased siRNAs in maize and
rice anthers, for instance.

We like to use a cutoff of 95th to 99th percentile for phasing scores. Only
the best scores are of interest. Phasing is relative, not absolute of
course.

Hope this helps.

On Fri, Dec 4, 2015 at 4:09 PM, xingwu2 <notifications@github.com> wrote:

> Hi Alex:
>
> I used the ShortStack-3.3 to analyze my soybean small RNAseq data. I found
> many phased siRNAs have dicercall not equal to 21nt, for example 24nt, is
> this normal? Also If I want to set a confidence cutoff on PhaseScore, what
> would be a reasonable value for it? How about 100?
>
> Best
>
> Xing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MikeAxtell/ShortStack/issues/33>.
>



-- 
Michael J. Axtell, Ph.D.
Associate Professor
Dept. of Biology
Penn State University
http://sites.psu.edu/axtell
Twitter: @MikeAxtell

**Comment by xingwu2** [comment]
OH..I am so sorry. I apologize, Dr. Axtell. 

Thank you so much for still answering my question. :D

Have a nice weekend. 

Xing
