### ISSUE TITLE
ShortStack3.3 MIRNA loci description files

### ISSUE THREAD

**Issue by alicelunardon** [MikeAxtell/ShortStack#35]
Mismatches in the small RNA sequences mapped against the MIRNA hairpin loci are reported as lower-case letters. When a mismatch is found for a thymine, a "t" is reported instead of "u", while mapped bases are reported as "ACGU".
Alice

**Comment by MikeAxtell** [comment]
Thanks for pointing this out. Bug fixed as of version 3.5
