### ISSUE TITLE
Error running TEST_DATA

### ISSUE THREAD

**Issue by d3d1y** [MikeAxtell/ShortStack#38]
I tried running your test data and got an error. There was some sort of error when I tried unpacking the original tgz file, but since I got all the files the README said I should, I went ahead with the test. So there may be something wrong with the TEST_DATA tgz.
`ShortStack --adapter CTGTAGGC --readfile SRR051927_even.fastq.gz SRR051927_odd.fastq.gz --outdir test1 --genomefile Athaliana_167.fa`
...
`Tue May 24 13:48:18 PDT 2016
Adapter trimming input reads file SRR051927_even.fastq.gz with adapter CTGTAGGC
    FATAL in sub-routine trim_fastq: Invalid FASTQ format in input reads file SRR051927_even.fastq.gz at
    @SRR051927.535492 HWI-EAS121_1_FC20689AAXX:4:29:421:706 length=36
    ATGATTATGGACCGTCGGATCATTCTGTATGCACCT
    +SRR051927.535492 HWI-EAS121_1_FC20689AAXX:4:29:421:706 length=36
    7:=:=:7::711111111)1..3..3113.33./)+))""""""6:503 length=36`

**Comment by MikeAxtell** [comment]
Thank you for letting me know. Yes, it looks like that tarball was
corrupted. I rebuilt it, tested it, and have uploaded a fixed version to
the same location (
http://axtelldata.bio.psu.edu/data/ShortStack_TestData/TEST_DATA.tgz).
Please let me know if that solves the issue on your end.

- Mike Axtell


On Tue, May 24, 2016 at 5:20 PM, d3d1y <notifications@github.com> wrote:

> I tried running your test data and got an error. There was some sort of
> error when I tried unpacking the original tgz file, but since I got all the
> files the README said I should, I went ahead with the test. So there may be
> something wrong with the TEST_DATA tgz.
> ShortStack --adapter CTGTAGGC --readfile SRR051927_even.fastq.gz
> SRR051927_odd.fastq.gz --outdir test1 --genomefile Athaliana_167.fa
> ...
> Tue May 24 13:48:18 PDT 2016
> Adapter trimming input reads file SRR051927_even.fastq.gz with adapter
> CTGTAGGC
> FATAL in sub-routine trim_fastq: Invalid FASTQ format in input reads file
> SRR051927_even.fastq.gz at
> @SRR051927.535492 HWI-EAS121_1_FC20689AAXX:4:29:421:706 length=36
> ATGATTATGGACCGTCGGATCATTCTGTATGCACCT
> +SRR051927.535492 HWI-EAS121_1_FC20689AAXX:4:29:421:706 length=36
> 7:=:=:7::711111111)1..3..3113.33./)+))""""""6:503 length=36
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MikeAxtell/ShortStack/issues/38>
>



-- 
Michael J. Axtell, Ph.D.
Associate Professor
Dept. of Biology
Penn State University
http://sites.psu.edu/axtell
Twitter: @MikeAxtell

**Comment by d3d1y** [comment]
This link is still pointing to the old TEST_DATA.tgz:
http://axtelldata.bio.psu.edu/data/ShortStack_TestData/

**Comment by MikeAxtell** [comment]
No it's not. TEST_DATA.tgz has been updated. See the file modification
date. Please download and check to see if it is OK now.

On Wed, May 25, 2016 at 11:38 AM, d3d1y <notifications@github.com> wrote:

> This link is still pointing to the old TEST_DATA.tgz:
> http://axtelldata.bio.psu.edu/data/ShortStack_TestData/
> [ICO] Name Last modified Size Description
> [PARENTDIR] Parent Directory -
> [ ] README 2015-08-14 14:48 239
> [ ] TEST_DATA.tgz 2016-05-25 09:43 198M
> [DIR] old/ 2015-08-14 14:46 -
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MikeAxtell/ShortStack/issues/38#issuecomment-221613850>
>



-- 
Michael J. Axtell, Ph.D.
Associate Professor
Dept. of Biology
Penn State University
http://sites.psu.edu/axtell
Twitter: @MikeAxtell

**Comment by d3d1y** [comment]
Sorry. I originally thought that it was the old file because I was still getting an error trying to unpack it. I've downloaded the new file and am still getting this error:
[dbrooks@dbrooks01-centos shortstack]$ tar -zxvf TEST_DATA.tgz 
./._TEST_DATA
TEST_DATA/
TEST_DATA/._.DS_Store
TEST_DATA/.DS_Store
TEST_DATA/._ath_hp_mb19.txt
TEST_DATA/ath_hp_mb19.txt
TEST_DATA/._Athaliana_167.fa
TEST_DATA/Athaliana_167.fa
tar: Skipping to next header

gzip: stdin: invalid compressed data--crc error

gzip: stdin: invalid compressed data--length error
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by MikeAxtell** [comment]
My apologies. We might have an issue with our http server, because you're
right, when I just checked again I also found that new .tgz corrupted and
un-extractable.

I just re-uploaded again, then checked the new download and it worked. Can
you check?

I'm not sure what is going on but I need to take a look at my http server.

Sorry for the hassle.

I dumped a copy of the file here ::
https://psu.box.com/s/i6m4fpumh51lrqs8vsedq1m5w2nkrg9o

.. and maybe that will work better. I will take a look at my fileserver
soon to see if there is some issue.

Sorry again and thanks for letting me know.

- Mike


On Wed, May 25, 2016 at 3:09 PM, d3d1y <notifications@github.com> wrote:

> Sorry. I originally thought that it was the old file because I was still
> getting an error trying to unpack it. I've downloaded the new file and am
> still getting this error:
> [dbrooks@dbrooks01-centos shortstack]$ tar -zxvf TEST_DATA.tgz
> ./.
>
> *TEST_DATA TEST_DATA/ TEST_DATA/.*.DS_Store
> TEST_DATA/.DS_Store
> TEST_DATA/._ath_hp_mb19.txt
> TEST_DATA/ath_hp_mb19.txt
> TEST_DATA/._Athaliana_167.fa
> TEST_DATA/Athaliana_167.fa
> tar: Skipping to next header
>
> gzip: stdin: invalid compressed data--crc error
>
> gzip: stdin: invalid compressed data--length error
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MikeAxtell/ShortStack/issues/38#issuecomment-221676142>
>



-- 
Michael J. Axtell, Ph.D.
Associate Professor
Dept. of Biology
Penn State University
http://sites.psu.edu/axtell
Twitter: @MikeAxtell

**Comment by d3d1y** [comment]
Happiness!
It worked great this time. Thanks for keeping after this. I'm pushing for my group to use ShortStack for miRNA annotation, and I'm excited to see what it can do.
