### ISSUE TITLE
Recongition of file extensions is patchy

### ISSUE THREAD

**Issue by adomingues** [MikeAxtell/ShortStack#39]
Hi Mike,

I am now testing short for a variety of applications, and there are few errors/bugs/suggestions that I came across. To keep things tidy I will create a separate issue for each - apologies for the perceived spam.

Quite often reads are pre-processed before mapping - adapter removal is one of the most common - and the fastq files are renamed to keep track of the process. However, it seems like Short stack does not tak that in consideration and is very sensible to the the file extensions. In this example:
  
> readfile PolII_2_2nd_run does not end in a valid file suffix  suffix was .cutadapt.fastq.gz

the file does have have a `fastq.gz` extension (plus `.cutadapt`) and yet ShortStack is very strict about it. Is this intended and would it be possible to change this (somewhat unexpected) behaviour?

Cheers,
António

**Comment by MikeAxtell** [comment]
Thanks Antonio. Yes, current version is strict with acceptable file extensions, which are defined as anything after the first '.' in the file name. I might try to change in next release, but could be slow. Meanwhile, you're welcome to fork and hack at it if you like.

**Comment by adomingues** [comment]
Thank you for looking into this. I might pick up my Perl book again and hack a solution at some point. No promises though.

**Comment by MikeAxtell** [comment]
Version 3.5 now is more tolerant of file extensions on input files and fixes this specific issue. Thanks for the suggestion!
