### ISSUE TITLE
Adding extra flags to bowtie

### ISSUE THREAD

**Issue by adomingues** [MikeAxtell/ShortStack#40]
Right now bowtie is called via ShortStack and only a few parameters can be used:
`--bowtie_cores`
`--mismatches`
`--bowtie_m`

whilst I understand the option to limit this and keep control of the mapping by ShortStack,  it would be useful to send other (arbitrary) options to bowtie by setting something like `--bowtie_extra "--best --strata --trim5 4 --trim3 4"`, that then gets sen to bowtie. You get the idea. The `--best --strata` options are particularly important for some bowtie versions that show strand bias. 

On bowtie versions, ShortStack looks for the version in `PATH`. Sometimes I need to use different version that are not in `PATH`, and in that situation call I `export PATH=${TOOL_BOWTIE}:$PATH` before running ShortStack. Would it be possible to have a `--bowtie_path` argument in ShortStack? That would give more flexibility to test different bowtie versions.

**Comment by adomingues** [comment]
Ah, looking at the logs I see that `--best --strata` are already set. I will leave the suggestion open because it might still make sense to pass extra Parameters to bowtie.

**Comment by MikeAxtell** [comment]
Thanks Antonio. 

Definitely I know about the strand bias issue, and ShortStack eliminates it. This was tested extensively. Internally, ShortStack 3.x when it aligns is always calling -a and also always calling --best and --strata when appropriate (e.g., when mismatches are set to not zero).  I appreciate your suggestion to allow users to pass in arbitrary bowtie command line parameters, but I worry that it is very easy that way for users to do various things that will break ShortStack's parsing of the alignment stream, which is a little intricate. There would have to be a lot of tedious code to check the user's input to avoid duplicate / conflicting parameters relative those that are hard-coded into ShortStack. I'll think about it but no guarantees that I will implement. 

As far as PATH goes, sure, I could implement that in the next release.

Thank you for the interest and suggestions.

**Comment by MikeAxtell** [comment]
Thanks again for these two suggestions. I've given them some thought and feel that the risk to great to break the internal processing if I allow users to pass in their own bowtie parameters. And regarding the bowtie_path .. seems like it can be that hard to just modify your own PATH before runs instead of going to trouble to add another option to ShortStack itself. Thanks and hope you understand.
