### ISSUE TITLE
--outdir 

### ISSUE THREAD

**Issue by rmonti** [MikeAxtell/ShortStack#49]
when I use the option '--outdir 2017126_125550_ShortStack_out/detect/ '

The output directory is '2017126_125550_ShortStack_outdetect' instead of a subfolder inside of '2017126_125550_ShortStack_out'

Probably not the way it is meant to work.

Also, if the output directory specified already exists, ShortStack won't run. While I think that is a reasonable behavior in order to prevent files from being overridden, you may want to mention it in the manual.

**Comment by MikeAxtell** [comment]
Fixed in release 3.7.1
