### ISSUE TITLE
expected index names

### ISSUE THREAD

**Issue by rmonti** [MikeAxtell/ShortStack#50]
Hi Mike,

Here is another small issue when I use non-standard file-names:

my genome-file is named like this:
Bdistachyon_314_v3.0_processed.fa

the folder contains the bowtie index files:
Bdistachyon_314_v3.0_processed.*.ebwt

ShortStack does not recognize them, indstead, it produces its own index files called:

Bdistachyon_314_v3.*.ebwt

**Comment by MikeAxtell** [comment]
Fixed in release 3.7.1

**Comment by ewilkie** [comment]
With ShortStack version 3.8.4, if you place the bowtie indexes, .fa and .fai files in same dir as your fastq files, this issue is resolved. At least for my linux configuration.

**Comment by MikeAxtell** [comment]
Thanks, will take a look when I have a chance. Somehow filename parsing has become my nemesis!

**Comment by MikeAxtell** [comment]
Just closing out old issues today .. this one is fixed in the current release (3.8.5). Thanks again!
