### ISSUE TITLE
Which parameters should I use for filtering raw data?

### ISSUE THREAD

**Issue by DiegoZvallo** [MikeAxtell/ShortStack#63]
Hi Mike, I know that this is not a ShortStack related question (at least not directly), but I was wondering which parameters did you use for small RNA data with Trimmomatic? I only use it for mRNA-Seq data, but when it comes to sRNAs I always used FASTX-Toolkit.
Best whishes 

Diego

**Comment by MikeAxtell** [comment]
Hi, somehow I missed this question when you sent it earlier this summer, sorry.

I haven't used trimmomatic. I use cutadapt, with settings 

`-a [adapter_sequence] --discard-untrimmed -m 16 --max-n=0`
