### ISSUE TITLE
How should we adjust the parameters according to the 2018 Criteria suggested in PlantCell

### ISSUE THREAD

**Issue by boya888** [MikeAxtell/ShortStack#80]
Dear ShortStack colleagues,
Thanks for sharing this wonderful tool for analysis of small RNAs.

According to the 2018 Criteria you published in www.plantcell.org/cgi/doi/10.1105/tpc.17.00851, I think it is difficult to adjust the parameters used in one of our previous analysis.
It seems that RNAfold is packaged into the ShortStack, thus I send this message to modify the parameters accordingly.

the hairpin RNA structures containing mappable sequences were predicted from the flank 120 nt sequences using RNAfold software.
Sequences that met the following criteria were then considered to be novel miRNA precursors. The criteria for secondary structure prediction were: 
(1) number of nucleotides in one bulge in stem(<=12) 
(2) number of base pairs in the stem region of the predicted hairpin (>=16) 
(3) cutoff of free energy (<= -15 kCal/mol) 
(4) length of hairpin (up and down stems + terminal loop >=50) 
(5) length of hairpin loop (<=200)
(6) number of nucleotides in one bulge in mature region (<=4) 
(7) number of biased errors in one bulge in mature region(<=2) 
(8) number of biased bulges in mature region (<=2) 
(9) number of errors in mature region (<=4) 
(10) number of base pairs in the mature region of the predicted hairpin (>=12) 
(11) percent of mature in stem (>=80). 
Moreover, Minimum free energy index (MFEI) was taken into account for evaluating the confidence of novel miRNAs, with the expected value (≥0.85)

**Comment by MikeAxtell** [comment]
So, umm, sorry I didn't answer this for more than two years! Kind of embarrassing. 

Anyway this is great point. Loci that are called "MIRNA" by ShortStack currently are NOT guaranteed to meet all of the criteria that Blake and I suggested in that Plant Cell paper. That's an issue I am aware of, and that I hope to fix in the next major release of ShortStack. Stay tuned.
