### ISSUE TITLE
Separating the known miRNAs from the new clusters identified in ShortStack

### ISSUE THREAD

**Issue by tarakaramji** [MikeAxtell/ShortStack#84]
Hi,

As per the instructions, i have run the pipeline using the denovo-clustering and after which I provided the loci file of known miRNAs from miRBase. How am I supposed to get the ones which are not known (novel miRNAs)? 
Please suggest
Thank you

Regards,
Ramji

**Comment by MikeAxtell** [comment]
Hello, thank you for your message.

ShortStack is not designed to explicitly check against previous
annotations. You could use a tool like bedtools intersect to find overlaps
between de novo loci found by ShortStack and pre-existing annotations.

Best Wishes,
Mike

On Sun, Oct 28, 2018 at 7:20 AM Taraka Ramji Moturu <
notifications@github.com> wrote:

> Hi,
>
> As per the instructions, i have run the pipeline using the
> denovo-clustering and after which I provided the loci file of known miRNAs
> from miRBase. How am I supposed to get the ones which are not known (novel
> miRNAs)?
> Please suggest
> Thank you
>
> Regards,
> Ramji
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMikeAxtell%2FShortStack%2Fissues%2F84&data=02%7C01%7Cmja18%40psu.edu%7Cc0c79afe88ca4bd7701c08d63cc75d33%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636763224303625750&sdata=WUvNJL4WUipaTqQsPddzgpyZnNf13sC%2B0kDxLe14CQc%3D&reserved=0>,
> or mute the thread
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGiXiXZE46JgCsWncy_3rm6HmdcprvF8ks5upZL5gaJpZM4X96J-&data=02%7C01%7Cmja18%40psu.edu%7Cc0c79afe88ca4bd7701c08d63cc75d33%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636763224303635746&sdata=CoF7%2Fo62%2F9EEANMnQzsImhX4zbanuO5apxwe7ya3Ba4%3D&reserved=0>
> .
>


-- 
Michael J. Axtell, Ph.D.
Professor of Biology
The Pennsylvania State University
http://sites.psu.edu/axtell
http://plantsmallrnagenes.science.psu.edu

**Comment by juancrescente** [comment]
hi @MikeAxtell!
Any hints about how to identify known mature miRNAs? 

Right now I'm doing a blast search (-task blastn) using the MajorRNA column as query and mature sequences from miRBase as subject. Then, filtering out all hits with more than 2 mismatches and alignment length less than the mature miRNA length minus 2. From your own paper:

> Defining a “conserved” miRNA is an inherently slippery concept. When applied to miRNAs, conservation generally refers to the accumulation of identical or near-identical (one or two nucleotide differences) mature miRNA sequences, although the miRNA* and some flanking hairpin sequence also sometimes demonstrate conservation

Do you think this approach is ok?

**Comment by MikeAxtell** [comment]
ShortStack4 implements a `knownRNAs` file that nucleates *MIRNA* searching at genomic locations where user-provided RNAs are aligned to the reference genome. ShortStack4 is currently in alpha testing and can be accessed on the ShortStack4 branch.
