### ISSUE TITLE
Multiple bam files input

### ISSUE THREAD

**Issue by kaushik-tlx** [MikeAxtell/ShortStack#86]
Hello,

Is there a way to input multiple bam files for downstream analysis using ShortStack? The program takes multiple input read files (space separated) for aligning, however does not recognize multiple bam files to perform just downstream analysis. I am able to get around the problem by merging the bam files first and using that single merged bam file as input.

Just wondering if I am doing something wrong.

Thanks,
Kaushik.

**Comment by MikeAxtell** [comment]
Hi Kaushik.

Nope, only one bam file. Merging first yourself is the solution if you
don't want to let ShortStack also handle the alignments by feeding in
multiple read files. Note that the Counts.txt file will contain read counts
per locus per read group if the single input BAM file had more than one
read-group.

Cheers,
Mike


On Fri, Dec 7, 2018 at 4:39 PM Kaushik Panda <notifications@github.com>
wrote:

> Hello,
>
> Is there a way to input multiple bam files for downstream analysis using
> ShortStack? The program takes multiple input read files (space separated)
> for aligning, however does not recognize multiple bam files to perform just
> downstream analysis. I am able to get around the problem by merging the bam
> files first and using that single merged bam file as input.
>
> Just wondering if I am doing something wrong.
>
> Thanks,
> Kaushik.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMikeAxtell%2FShortStack%2Fissues%2F86&data=02%7C01%7Cmja18%40psu.edu%7C05856d67780347e1266f08d65c8c7da4%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636798155814675272&sdata=G%2F%2BbjgZKOu8KkNqnm3uRIFTuwHWLQxvEqUfEQmYupcw%3D&reserved=0>,
> or mute the thread
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGiXiUqCXoEdw-yT5-r_p38Wpd3V94bHks5u2uAYgaJpZM4ZJL-A&data=02%7C01%7Cmja18%40psu.edu%7C05856d67780347e1266f08d65c8c7da4%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636798155814675272&sdata=2vXRUDCAo%2FNnO2pJbKGJutmZClmgyKlNvxgxw1ZY8gY%3D&reserved=0>
> .
>


-- 
Michael J. Axtell, Ph.D.
Professor of Biology
The Pennsylvania State University
http://sites.psu.edu/axtell
http://plantsmallrnagenes.science.psu.edu
