### ISSUE TITLE
ShortStack padding bug?

### ISSUE THREAD

**Issue by bbermudez** [MikeAxtell/ShortStack#89]
Dear Michael Axtell:

According to the README the pad parameter can be an integer between 0 and 50000. “Must be an integer between 0 and 50000. Default: 75". But whenever I run ShortStack with padding 0, it reports in Log.txt that it actually ran with default 75.

I made a toy example with a small genome having two adjacent reads (0 nucleotides between them), 

genome.fasta
>TRINITY_DN11606_c2_g1_i1
TTGCATGCGGTGGCTCCGCACACGTTTGATTGGAACGTGGTCAATGGTAGAAACCCCCCG
AGCGCTAGAGCACTCTGGCTCTACCGTTCGGTTGACACGTTCAGGTTCGGTGGGACCGGC

reads.fa
>read1
TGGCTCCGCACACGTTTGAT
>read2
TGGAACGTGGTCAATGGTAG

According to the README the pad parameter is at follows “Initially found clusters of small RNAs will be merged if the distance between them is less than or equal to the value of pad”. For the mentioned example I would interpret that using padding 1 should result in one single cluster, however I get two different clusters even when the distance between them is 0 nucleotides. When I increase the pad parameter to 2 I now get one single cluster.

The instruction that I used was:
ShortStack --mincov 1 --pad 2 --readfile reads_distance_1.fa --genomefile genome.fasta

Maybe I am misinterpreting something, 

I performed these tests with ShortStack version 3.8.5

**Comment by MikeAxtell** [comment]
Yeah, umm, sorry for not responding for over a year ! 
I will run this down in the next major release, which I have begun working on.

**Comment by bbermudez** [comment]
Don’t worry Mike

Looking forward using the new ShortStack version!

Cheers,
José Roberto

**Comment by MikeAxtell** [comment]
ShortStack version 4 is now available for alpha testing on the ShortStack4 branch. It will be merged into master and released once we complete testing. But it should solve this issue.
