### ISSUE TITLE
Double tab in Counts.txt

### ISSUE THREAD

**Issue by juancrescente** [MikeAxtell/ShortStack#91]
Hi!

I've noticed in the Counts.txt, unplaced sRNA have double tab between the _main_ and first condition column.

`UUUUAUUAUGAUCCAUUUCGCGUGGAAUUCUGGGUGCCAAGGAACUCCAG	NA	114		37	15	37	25
`
In this case, between 114 and 37. What I had to do to solve this was:

`tr -s '\t' '\t' < counts.csv > counts.fixed.csv`

This could lead to some issues when doing downstream analysis. 

Regards!

**Comment by acontrerasg** [comment]
Thanks for leaving an easy solution! I was also having troubles with it

**Comment by MikeAxtell** [comment]
Yikes. I will make sure this gets fixed in the next major release. Actually I think reporting the unplaced sRNAs in the same file as the locus counts was poor decision in the first place, and I intend to separate them in the next major release.

**Comment by MikeAxtell** [comment]
A new major update to ShortStack, version 4.0, is now in alpha testing: It is available on the ShortStack4 branch. Once we complete alpha testing this will be merged to master and released. But for now you are welcome to test it out. This glitch in the Counts.txt file has been fixed .. the unplaced sRNAs have been removed altogether.
