### ISSUE TITLE
Which version of the ShortStack is selected to predict miRNAs in long hairpin structure

### ISSUE THREAD

**Issue by Rease123** [MikeAxtell/ShortStack#93]
Hello,
The species I studied (animal) had many conserved miRNAs with long hairpin structure because it was the first identification. Please, which version of ShortStack should I use? I want to generate a file for  the inverted repeats with reference to your 2013 publication, but I can't find the  script ‘invert_it.pl’. 
Thanks,

**Comment by MikeAxtell** [comment]
Sorry to leave this here for over a year. I'm just catching up with open issues now. 
invert_it.pl is obsolete for a long time now .. the most recent version of ShortStack does not use that tool anymore. The 2013 paper is a fair bit of date I'm afraid. As with most software, your best bet is to use the most recent release of the tool. Hope this helps.
