### ISSUE TITLE
Characteristics of siRNA clusters 

### ISSUE THREAD

**Issue by RubioB** [MikeAxtell/ShortStack#95]
Hi, 
I was wondering if is it possible to obtain a folder containing the characteristics of each of the clusters which do not correspond to miRNA ? The idea would actually be to have a folder with the same type of files as the one created for the miRNA clusters.

Thank you in advance for your reply, 

Bernadette

**Comment by MikeAxtell** [comment]
Sorry to have ignored this question for so long. I am finally tackling the pile of open issues.
Anyway, interesting suggestion, but I probably won't implement it. There's not much more information I can think of that isn't already in the Results.txt output file.

Please forgive the slow response and thanks for your question!
