### ISSUE TITLE
small RNA annotation using --locifile file

### ISSUE THREAD

**Issue by atvivek** [MikeAxtell/ShortStack#96]
I have used Shortstack for some time now but I don't understand how to include strand information other than Chr:start-end  in the loci file to annotate accordingly. Any help on this would be greatly appreciated.

Regards,
A.T.Vivek

**Comment by BioFalcon** [comment]
Might want to look at the --strand_cutoff parameter. If your reads align to both strands and do not pass the threshold, ShortStack will not assign a strand.

**Comment by atvivek** [comment]
Thanks@BioFalcon. Your suggestion was helpful.
